version: '3.8'

services:
  app2:
    build: .
    deploy:
      replicas: 2
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app2.rule=Host(`app2.docker.localhost`)"
      - "traefik.http.routers.app2.entrypoints=websecure"
      - "traefik.http.routers.app2.tls=true"
      - "traefik.http.services.app2.loadbalancer.server.port=5000"

networks:
  proxy:
    external: true