version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #ports:
    #  - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - db_network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mysql-router.entrypoints=mysql"
      # IMPORTANT: If using MySQL 8.1.0+ and sending SNI, use your subdomain here:
      # - "traefik.tcp.routers.mysql-router.rule=HostSNI(`db.rapterxcode.online`)"
      # Otherwise, for single DB on 3306, HostSNI(`*`) is usually fine.
      - "traefik.tcp.routers.mysql-router.rule=HostSNI(`*`)" # Keep this if you're unsure about client SNI or on older MySQL
      - "traefik.tcp.routers.mysql-router.service=mysql-service"
      - "traefik.tcp.services.mysql-service.loadbalancer.server.port=3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8011:80"
    networks:
      - db_network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`db.rapterxcode.online`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

networks:
  db_network:
    driver: bridge
  proxy:
    external: true